on:
  [workflow_dispatch]

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          status: ${{ job.status }}
          nodetail: true
          title: "${{ job.status }}: Update EclipseBuilder to ${{ github.sha }}"
          description: |
            [Eclipse builder](https://rockymoto517.github.io/eclipsebuilder/) has been updated.
          color: 0x00ff00
          username: "Eclipse Builder"
          avatar_url: ${{ secrets.AVATAR_URL }}
