# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run predeploy
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Set which folders to exclude
        # exclude_assets: ''
        # Set a target branch for deployment.
        #publish_branch: # optional, default is gh-pages
        # Set an input directory for deployment.
        #publish_dir: # optional, default is public
        # Set an destination subdirectory for deployment.
        #destination_dir: # optional, default is 
        # Set Git user.name
        #user_name: # optional
        # Set Git user.email
        #user_email: # optional
        # Set a custom commit message with a triggered commit hash
        #commit_message: # optional
        # Set a custom full commit message without a triggered commit hash
        #full_commit_message: # optional
        # Set tag name
        #tag_name: # optional
        # Set tag message
        #tag_message: # optional
        # Set custom domain
        # cname: pd2build.ar

    - name: Capitlize status
      run: |
        STATUS_VAR=${{ job.status }}
        CAP_STATUS_VAR=$(echo "$STATUS_VAR" | sed 's/^\(.\)/\U\1/')
        echo "CAP_STATUS_VAR=$CAP_STATUS_VAR" >> $GITHUB_ENV
        echo "${{ github.event.head_commit.message }}"

    - name: Discord Webhook
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.WEBHOOK_URL }}
        status: ${{ job.status }}
        nodetail: true
        title: "${{ env.CAP_STATUS_VAR }}: Update EclipseBuilder"
        description: |
          Eclipse builder has been updated to [${{ github.sha }}](https://github.com/rockymoto517/eclipsebuilder/commit/${{ github.sha }}).

          https://rockymoto517.github.io/eclipsebuilder/
          
          ${{ github.event.head_commit.message }}
        color: 0x00ff00
        username: "Eclipse Builder"
        avatar_url: ${{ secrets.AVATAR_URL }}
